// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables');
}
console.log('SUPABASE_URL:');
console.log('SUPABASE_PUBLISHABLE_KEY:');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export interface QuizSession {
  id: string;
  quiz_id: string;
  current_question_index: number;
  status: 'waiting' | 'active' | 'paused' | 'question_ended' | 'ended';
  time_remaining: number;
  started_at: string;
  ended_at: string | null;
  created_by: string;
}

export interface QuizParticipantAnswer {
  id: string;
  session_id: string;
  question_id: string;
  participant_id: string;
  answer: string;
  is_correct: boolean;
  points_earned: number;
  response_time: number;
  created_at: string;
}

export interface QuizParticipant {
  id: string;
  session_id: string;
  user_id: string;
  total_points: number;
  joined_at: string;
}