// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msqohkabyjeoqvvfbbgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zcW9oa2FieWplb3F2dmZiYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjQ2NDMsImV4cCI6MjA2MTIwMDY0M30.t-s1xo0TiK2BUGgB-hWazRtALt0GVv2O8Ber1MNEbVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);